name: Build and Push to GHCR

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: |
        echo "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" | docker login ghcr.io --username "oosborgschmitz" --password-stdin

    - name: Build Docker Image
      run: |
        IMAGE_NAME=ghcr.io/oosborgschmitz/my-web-app:latest
        docker build -t $IMAGE_NAME .

    - name: Push Docker Image to GHCR
      run: |
        IMAGE_NAME=ghcr.io/oosborgschmitz/my-web-app:latest
        docker push $IMAGE_NAME