name: Trigger auto deployment for general-app-testing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/general-app-testing-AutoDeployTrigger-605a61e3-c716-4228-a986-8b15608e3881.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GENERALAPPTESTING_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: ./Dockerfile
          registryUrl: ghcr.io/sse-movies/general-app-testing:latest
          registryUsername: ${{ secrets.GENERALAPPTESTING_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GENERALAPPTESTING_REGISTRY_PASSWORD }}
          containerAppName: general-app-testing
          resourceGroup: SSE-movies
          imageToBuild: ghcr.io/sse-movies/general-app-testing:latest/ghcr.io:${{ github.sha }}
          
            

     

